name: Pull Request checks

on:
  pull_request: 
    branches: [ main ]

jobs:
  build-check:
    name: Test Install 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: NPM Install
        run: npm install
      - name: Test
        run: npm run test